apiVersion: v1
kind: Pod
metadata:
  name: firstapp
  labels:
    app: firstapp
spec:
  containers:
    - name: firstapp
      image: davsdocker/firstapp:$DOCKER_TAG
      ports:
        - containerPort: 9090
